from time import sleep
Arduino = Runtime.start("Arduino","Arduino")
servo01 = Runtime.start("servo01","Servo")
Arduino.connect("COM3")
servo01.attach(Arduino.getName(), 30)
servo01.setRest(80)
servo01.enableAutoEnable(1)
servo01.enableAutoDisable(0)
sleep(3)
servo01.moveTo(40)
sleep(3)
servo01.rest()
