!!org.myrobotlab.service.config.LocalSpeechConfig
audioFile: i01.mouth.audioFile
autoStartPeers: true
blocking: false
mute: false
speechRecognizers:
- i01.ear
substitutions: null
type: LocalSpeech
voice: Harry
