!!org.myrobotlab.service.config.MarySpeechConfig
audioFile: i01.mouth.audioFile
autoStartPeers: true
blocking: false
mute: false
speechRecognizers:
- i01.ear
substitutions: null
type: MarySpeech
voice: Obadiah
