adaFruitRight = Runtime.createAndStart("adaFruitRight","Adafruit16CServoDriver")
sleep(1)
adaFruitRight.connect("COM4")
# Set I2C address ( x40 = 4*16 + 0 = 64 )
#adaFruitRight.setI2CAddress(64)
sleep(1)
# create a new servo
thumb = Runtime.createAndStart("Thumb", "Servo")
sleep(1)
elbow = Runtime.createAndStart("Elbow", "Servo")
sleep(1)
# attach it to the pwm board - pin 3 & 8
sleep(1)
thumb.attach(adaFruitRight,3)
elbow.attach(adaFruitRight,8)
#adaFruitRight.attach(thumb,3)
thumb.setMinMax(8,142)
elbow.setMinMax(0,180)
