i01 = Runtime.createAndStart("i01", "InMoov")
i01.opencv = Runtime.createAndStart("i01.opencv", "OpenCV")
i01.opencv.setCameraIndex(0)
i01.opencv.removeFilters()
i01.opencv.addFilter("PyramidDown")
i01.opencv.addFilter("Gray")
i01.opencv.addFilter("FaceDetect")
i01.opencv.setDisplayFilter("FaceDetect")
i01.opencv.capture()
