inmoov = Runtime.createAndStart("inmoov","InMoov")
inmoov.startRightHand("COM7")
inmoov.rightHand.index.setMinMax(0,160)
inmoov.rightHand.thumb.setMinMax(55,135)
inmoov.rightHand.majeure.setMinMax(50,170)
inmoov.rightHand.ringFinger.setMinMax(48,145)
inmoov.rightHand.pinky.setMinMax(30,168)
sleep(1)
inmoov.rightHand.startLeapTracking()
# inmoov.rightHand.stopLeapTracking()